Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "neschan-wasm"

  config.vm.network "private_network", ip: "192.168.56.48"
  config.vm.synced_folder "../../", "/workspace/nes"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "bootstrap.sh"
end
